silant/backend/urls.py
from django.urls import path, include

from .views import *


urlpatterns = [
    path('maintenances/', MaintenanceListView.as_view(), name='maintenance_list'),
    path('complaints/', ComplaintListView.as_view(), name='complaint_list'),
    path('car/<pk>/maintenances', MaintenanceCarListView.as_view(), name='car_maintenance'),
    path('car/<pk>/complaints', ComplaintCarListView.as_view(), name='car_complaint'),
    path('maintenance/create', MaintenanceCreateView.as_view(), name='maintenance_create'),
    path('complaint/create', ComplaintCreateView.as_view(), name='complaint_create'),
    path('maintenance/<pk>/update', MaintenanceUpdateView.as_view(), name='maintenance_update'),
    path('complaint/<pk>/update', ComplaintUpdateView.as_view(), name='complaint_update'),
    path('maintenance/<pk>/delete', MaintenanceDeleteView.as_view(), name='maintenance_delete'),
    path('complaint/<pk>/delete', ComplaintDeleteView.as_view(), name='complaint_delete'),
    path('maintenance/<pk>/description/<atribute>', MaintenanceDescriptionView.as_view(),
         name='maintenance_description'),
    path('complaint/<pk>/description/<atribute>', ComplaintDescriptionView.as_view(), name='complaint_description'),

    path('', HomeView.as_view(template_name='/index.html'), name='home'),
    path('search/', CarSearchView.as_view(), name='car_search_list'),
    path('cars/', CarListView.as_view(), name='car_list'),
    path('car/<pk>/detail', CarDetailView.as_view(), name='car_detail'),
    path('car/create', CarCreateView.as_view(), name='car_create'),
    path('car/<pk>/update', CarUpdateView.as_view(), name='car_update'),
    path('car/<pk>/delete', CarDeleteView.as_view(), name='car_delete'),
    path('car/<pk>/description/<atribute>', CarDescriptionView.as_view(), name='car_description'),
]

silant/silant/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .api_router import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('backend.urls')),
    path('', include('users.urls')),
    path('api/', include(router.urls))

    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

silant/users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path('api/user', views.user, name='user'),
    path('api/login', views.issue_token, name='issue_token'),
]

silant/backend/models.py
import datetime
from django.db import models
from rest_framework.reverse import reverse

from users.models import CustomUser


# Справочник компаний
class Sersvice(models.Model):
    name = models.ForeignKey(CustomUser, verbose_name='Сервисная компания',
                             on_delete=models.CASCADE)
    description = models.TextField('Описание', max_length=500, null=True, blank=True)

    class Meta:
        verbose_name = 'Сервисная компания'
        verbose_name_plural = 'Справочник сервисных компаний'

    def __str__(self):
        return f'{self.name}'


# Справочник по модели трансмиссии
class ModTransmissionG(models.Model):
    class Meta:
        verbose_name = 'Модель трансмиссии'
        verbose_name_plural = 'Справочник моделей трансмиссии'

    name = models.CharField('Модель трансмиссии', max_length=64, unique=True)
    description = models.TextField('Описание', max_length=500, null=True, blank=True)
    
    def __str__(self):
        return f'{self.name}'


# Справочник по модели машины
class ModMashinsG(models.Model):
    class Meta:
        verbose_name = 'Модель машины'
        verbose_name_plural = 'Справочник моделей машины'

    name = models.CharField('Модель машины', max_length=64, unique=True)
    description = models.TextField('Описание', max_length=500, null=True, blank=True)
    
    def __str__(self):
        return f'{self.name}'


# Справочник по модели мотора
class ModMotorG(models.Model):
    class Meta:
        verbose_name = 'Модель мотора'
        verbose_name_plural = 'Справочник моделей мотора'

    name = models.CharField('Модель мотора', max_length=64, unique=True)
    description = models.TextField('Описание', max_length=500, null=True, blank=True)
    
    def __str__(self):
        return f'{self.name}'


# Справочник по модели ведущего моста
class ModDriveBridgeG(models.Model):
    class Meta:
        verbose_name = 'Модель ведущего моста'
        verbose_name_plural = 'Справочник моделей ведущего моста'

    name = models.CharField('Ведущий мост', max_length=64, unique=True)
    description = models.TextField('Описание', max_length=500, null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


# Справочник по модели управляемого моста
class ModControllBridgeG(models.Model):
    class Meta:
        verbose_name = 'Модель управляемого моста'
        verbose_name_plural = 'Справочник моделей управляемого моста'

    name = models.CharField('Управляемый мост', max_length=64, unique=True)
    description = models.TextField('Описание', max_length=500, null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


# Справочник по видам тех. обслуживания
class VidTOG(models.Model):
    class Meta:
        verbose_name = 'Вид технического обслуживания '
        verbose_name_plural = 'Справочник видов ТО'

    name = models.CharField('Вид ТО', max_length=64, unique=True)
    description = models.TextField('Описание', max_length=500, null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


# Справочник по характерам отказа
class NatureRefusalG(models.Model):
    class Meta:
        verbose_name = 'Характер отказа'
        verbose_name_plural = 'Справочник характеров отказа'

    name = models.CharField('Характер отказа', max_length=64, unique=True)
    description = models.TextField('Описание', max_length=500, null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


# Справочник по способам восстановления
class RecoveryMethodG(models.Model):
    class Meta:
        verbose_name = 'Способ восстановления'
        verbose_name_plural = 'Справочник способов восстановления'
    
    name = models.CharField('Способ восстановления', max_length=64, unique=True)
    description = models.TextField('Описание', max_length=500, null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


# Справочник клиентов
class ClientG(models.Model):

    name = models.ForeignKey(CustomUser, verbose_name='Клиент', on_delete=models.CASCADE)
    description = models.TextField('Описание', max_length=500, null=True, blank=True)

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиент'

    def __str__(self):
        return f'{self.name}'


# Справочник узлов отказа 
class FailureNodeReference(models.Model):
    class Meta:
        verbose_name = 'Узел отказа'
        verbose_name_plural = 'Справочник узлов отказа'

    name = models.CharField('Наименование узла', max_length=150, unique=True)
    description = models.TextField('Описание', max_length=5000, null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


# Таблица по машине
class Mashins(models.Model):
    class Meta:
        verbose_name = 'Машина'
        verbose_name_plural = 'Машины'

    zav_nom_mashins = models.CharField('Зав. № машины', primary_key=True, null=False, max_length=32, unique=True)
    model_mashins = models.ForeignKey(ModMashinsG, verbose_name='Модель машины', on_delete=models.CASCADE,
                                      related_name='model_mashins')

    model_motor = models.ForeignKey(ModMotorG, verbose_name='Модель двигателя', on_delete=models.CASCADE,
                                    related_name='model_motor')

    zav_nom_motor = models.CharField('Зав. № двигателя', max_length=32, blank=True, null=True)
    model_transmission = models.ForeignKey(ModTransmissionG, verbose_name='Модель трансмиссии',
                                           on_delete=models.CASCADE, related_name='model_transmission',
                                           blank=True, null=True)

    zav_nom_transmission = models.CharField('Зав. № трансмиссии', max_length=32, unique=True, blank=True, null=True)
    model_drive_bridge = models.ForeignKey(ModDriveBridgeG, verbose_name='Модель ведущего моста',
                                           on_delete=models.CASCADE, related_name='model_drive_bridgeclear',
                                           blank=True, null=True)

    zav_nom_drive_bridge = models.CharField('Зав. № ведущего моста', max_length=32, blank=True, null=True)
    model_controll_bridge = models.ForeignKey(ModControllBridgeG, verbose_name='Модель управляемого моста',
                                              on_delete=models.CASCADE, related_name='model_controll_bridge',
                                              blank=True, null=True)

    zav_nom_controll_bridge = models.CharField('Зав. № управляемого моста', max_length=100, blank=True, null=True)
    dogovor = models.CharField('Договор поставки №, дата', max_length=250, blank=True, null=True)  
    date_shipment = models.DateField('Дата отгрузки с завода', blank=True, null=True)  
    consignee = models.CharField('Грузополучатель (конечный потребитель)', max_length=250, blank=True, null=True)
    delivery_address = models.TextField('Адрес поставки (эксплуатации)', max_length=250, blank=True, null=True) 
    equipment = models.TextField('Комплектация (доп. опции)', max_length=250, blank=True, null=True)  
    client = models.ForeignKey(ClientG, verbose_name='Клиент', on_delete=models.CASCADE,
                               related_name='client', blank=True, null=True)
    service_company = models.ForeignKey(Sersvice, verbose_name='Сервисная компания', on_delete=models.CASCADE,
                                        related_name='service_company', blank=True, null=True)
      
    def __str__(self) -> str:
        return f'{self.zav_nom_mashins}'

    def get_absolute_url(self):
        return reverse('article-view', args=(str(self.pk),))


# Таблица по тех. обслуживанию
class TO(models.Model):
    class Meta:
        verbose_name = 'Техническое обслуживание'
        verbose_name_plural = 'Технические обслуживания'

    vid_TO = models.ForeignKey(VidTOG, verbose_name='Вид технического обслуживания', on_delete=models.CASCADE,
                               related_name='vid_TO')  # Вид ТО
    date_TO = models.DateField('Дата проведения ТО')
    mtbf = models.DecimalField('Наработка, м/час', max_digits=10, decimal_places=0)
    num_order = models.CharField('№ заказ-наряда', max_length=32, unique=True)
    date_order = models.DateField('Дата заказ-наряда')

    service_TO = models.ForeignKey(Sersvice, verbose_name='Сервисная компания', on_delete=models.CASCADE)
    mashins_TO = models.ForeignKey(Mashins, verbose_name='Машина', on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'{self.mashins_TO}'

    def get_absolute_url(self):
        return reverse('article-view', args=(str(self.pk),))


# Таблица рекламаций
class Complaint(models.Model):
    class Meta:
        verbose_name = 'Рекламация'
        verbose_name_plural = 'Рекламации'
    
    mashins_c = models.ForeignKey(Mashins, verbose_name='Машина', on_delete=models.CASCADE)
    date_refusal = models.DateField('Дата отказа', null=True, blank=True)
    mtdf_c = models.DecimalField('Наработка, м/час', max_digits=10, decimal_places=0)
    failure_node = models.ForeignKey(FailureNodeReference, verbose_name='Узел отказа',
                                     on_delete=models.CASCADE, related_name='failure_node')

    reason_refusal = models.ForeignKey(NatureRefusalG, verbose_name='Описание отказа',
                                       on_delete=models.CASCADE, related_name='reason_refusal')

    recovery_method = models.ForeignKey(RecoveryMethodG, verbose_name='Способ восстановления',
                                        on_delete=models.CASCADE, related_name='recovery_method',)
    spare = models.TextField('Используемые запасные части', max_length=1000, blank=True, null=True) 
    date_recovery = models.DateField('Дата восстановления', blank=True, null=True)
    downtime = models.IntegerField('Время простоя техники (дней)', default=0)
    service = models.ForeignKey(Sersvice, verbose_name='Сервисная компания', blank=True, null=True, on_delete=models.CASCADE)


    def downtime(self):

silant/backend/forms.py
from django import forms
from .models import Mashins, TO, Complaint


class CarForm(forms.ModelForm):
    class Meta:
        model = Mashins
        fields = '__all__'


class MaintenanceForm(forms.ModelForm):
    class Meta:
        model = TO
        fields = '__all__'
        widgets = {
            'vid_TO': forms.RadioSelect()
        }


class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = '__all__'

silant/backend/templates/backend/TO/maintenance_car.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'car_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<div class="client">
    <i class="silant silant-vehicle"></i>
    <h2>Машина " {{car.pk}} "</h2>
</div>
</div>
<nav class="nav-panel">
    <ul>
       <li><a href="{% url 'car_detail' car.pk %}"><i class="silant silant-service"></i> Сведения</a></li>
        <li class="active"><a href="{% url 'car_maintenance' car.pk %}"><i class="silant silant-maintenance"></i> ТО</a></li>
        <li><a href="{% url 'car_complaint' car.pk %}"><i class="silant silant-complaint"></i> Рекламации</a></li>
    </ul>
</nav>
<h3>Информация о комплектации и технических характеристиках Вашей техники</h3>
<div class="action-buttons">
    <a href="{% url 'maintenance_create' %}">Создать ТО</a>
</div>
<section class="area-table">
<table id="tableMaintenances" class="datatable" data-order='[0, "desc"]'>
    <thead class="datatable-thead">
        <tr>
            <th width="20%">Дата проведения ТО</th>
            <th width="30%">Вид ТО</th>
            <th width="20%">Наработка, м/час</th>
            <th width="20%">№ заказ-наряда</th>
            <th width="20%">Дата заказ-наряда</th>
            <th width="20%">Организация, проводившая ТО</th>
            <th width="3%"></th>
        </tr>
    </thead>
    {% for m in mashins_TO %}
        <tbody>
    {% for obj in m %}
        <tr>
            <td>{{obj.date_TO|date:"d.m.Y"}}</td>
            <td><span class="description-js" data-url="{% url 'maintenance_description' obj.pk 'vid_TO' %}">{{obj.vid_TO}}</span></td>
            <td>{{obj.mtbf}}</td>
            <td>{{obj.num_order}}</td>
            <td>{{obj.date_order|date:"d.m.Y"}}</td>
            <td><a href="{% url 'car_detail' obj.mashins_TO_id %}">{{obj.mashins_TO}}</a></td>
            {% if obj.service_TO %}
            <td><span class="description-js" data-url="{% url 'maintenance_description' obj.pk 'service_TO' %}">{{obj.service_TO}}</span></td>
            {% else %}
            <td>Нет компании</td>
            {% endif %}
            <td>
                <div class="actions">
                    <a class="update" href="{% url 'maintenance_update' obj.pk %}"><i class="fas fa-pencil-alt"></i></a>
                    <a class="delete delete-js" data-url="{% url 'maintenance_delete' obj.pk %}"><i class="fas fa-times"></i></a>
                </div>
            </td>
        </tr>
    {% endfor %}
        {% endfor %}
    </tbody>
</table>
</section>
{% endblock %}

silant/backend/templates/backend/TO/maintenance_confirm_delete.html
<a href="" class="modal-area"></a>
<form class="account-form modal-frame" method="post" action="{{request.path}}">
  {% csrf_token %}
    <span class="modal-exit"><i class="fas fa-times"></i></span>
    <div class="modal-body">
        <h1>Удаление</h1>
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
        {% endif %}
        <h4>Вы действительно хотите удалить {% if type == 'car' %}машину{% elif type == 'maintenance' %}ТО{% elif type == 'complaint' %}рекламацию{% endif %} {{object}}?</h4>
        <div class="modal-buttons">
            <button class="button" type="submit">Удалить</button>
            <span class="dummy-btn"></span>
            <button class="button button-alt cancel-js" type="reset">Отмена</button>
        </div>
    </div>
</form>

silant/backend/templates/backend/TO/maintenance_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'maintenance_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h2>Создание ТО</h2>
<form class="form" name="maintenanceForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div><label for="id_date_TO">{{form.date_TO.label}}</label> {{form.date_TO}}</div>
    <div class="united">
        <label for="mashins_TO">{{form.mashins_TO.label}}</label> {{form.mashins_TO}}
        <label for="mtbf">{{form.mtbf.label}}</label> {{form.mtbf}}
    </div>
    <div>{{form.type.label}}
        <div class="choices"> 
            {% for i, item in form.fields.type.widget.choices %}
            <div class="check-field">
                <input type="radio" name="type" value="{{i}}" id="id_type_{{i}}" {% for item in form.type.initial %}{% if i == item.pk %}checked=""{% endif %}{%endfor%}>
                <label for="id_type_{{i}}" class="check" name="active-check"><i class="fas fa-check"></i></label>
                <label for="id_type_{{i}}" class="check-text">{{item}}</label>
            </div>
            {% endfor %}
        </div> 
    </div>
    <div class="united">
        <label for="id_num_order">{{form.num_order.label}}</label> {{form.num_order}}
        <label for="id_date_order">{{form.date_order.label}}</label> {{form.date_order}}
    </div>
    <div><label for="id_service_TO">{{form.service_TO.label}}</label> {{form.service_TO}}</div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

silant/backend/templates/backend/TO/maintenance_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% csrf_token %}
<div class="client">
<i class="silant silant-client"></i>
{% if user.is_superuser %}
    <h2>Администратор</h2>
{% elif user.groups.first.name == "Менеджер" %}
    <h2>Менеджер {{user.first_name}}</h2>
{% elif user.groups.first.name == "Сервисная организация" %}
    <h2>Сервисная организация {{user.first_name}}</h2>
{% else %}
    <h2>Клиент {{user.first_name}} </h2>
{% endif %}
</div>
<nav class="nav-panel">
    <ul>
        <li><a href="{% url 'car_list' %}"><i class="silant silant-vehicle"></i> Машины</a></li>
        <li class="active"><a href="{% url 'maintenance_list' %}"><i class="silant silant-maintenance"></i> ТО</a></li>
        <li><a href="{% url 'complaint_list' %}"><i class="silant silant-complaint"></i> Рекламации</a></li>
    </ul>
</nav>
<h3>Информация о комплектации и технических характеристиках Вашей техники</h3>
<div class="action-buttons">
    <a href="{% url 'maintenance_create' %}">Создать ТО</a>
</div>
<section class="area-table">
<table id="tableMaintenances" class="datatable" data-order='[0, "desc"]'>
    <thead class="datatable-thead">
        <tr>
            <th width="20%">Дата проведения ТО</th>
            <th width="40%">Вид ТО</th>
            <th width="30%">Наработка, м/час</th>
            <th width="20%">№ заказ-наряда</th>
            <th width="20%">Дата заказ-наряда</th>
            <th width="30%">Машина</th>
            <th width="30%">Организация, проводившая ТО</th>
            <th width="3%"></th>
        </tr>
    </thead>
    {% for m in mashins_TO %}
        <tbody>
    {% for obj in m %}
        <tr>
            <td>{{obj.date_TO|date:"d.m.Y"}}</td>
            <td><span class="description-js" data-url="{% url 'maintenance_description' obj.pk 'vid_TO' %}">{{obj.vid_TO}}</span></td>
            <td>{{obj.mtbf}}</td>
            <td>{{obj.num_order}}</td>
            <td>{{obj.date_order|date:"d.m.Y"}}</td>
            <td><a href="{% url 'car_detail' obj.mashins_TO_id %}">{{obj.mashins_TO}}</a></td>
            {% if obj.service_TO %}
            <td><span class="description-js" data-url="{% url 'maintenance_description' obj.pk 'service_TO' %}">{{obj.service_TO}}</span></td>
            {% else %}
            <td>Нет компании</td>
            {% endif %}
            <td>
                <div class="actions">
                    <a class="update" href="{% url 'maintenance_update' obj.pk %}"><i class="fas fa-pencil-alt"></i></a>
                    <a class="delete delete-js" data-url="{% url 'maintenance_delete' obj.pk %}"><i class="fas fa-times"></i></a>
                </div>
            </td>
        </tr>
    {% endfor %}
        {% endfor %}
    </tbody>

</table>
</section>
{% endblock %}

silant/backend/templates/backend/TO/maintenance_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'maintenance_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h3>Изменение ТО</h3>
<form class="form" name="maintenanceForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div><label for="id_date_TO">{{form.date_TO.label}}</label> {{form.date_TO}}</div>
    <div class="united">
        <label for="mashins_TO">{{form.mashins_TO.label}}</label> {{form.mashins_TO}}
        <label for="mtbf">{{form.mtbf.label}}</label> {{form.mtbf}}
    </div>
    <div>{{form.type.label}}
        <div class="choices">
            {% for i, item in form.fields.type.widget.choices %}
            <div class="check-field">
                <input type="radio" name="type" value="{{i}}" id="id_type_{{i}}" {% for item in form.type.initial %}{% if i == item.pk %}checked=""{% endif %}{%endfor%}>
                <label for="id_type_{{i}}" class="check" name="active-check"><i class="fas fa-check"></i></label>
                <label for="id_type_{{i}}" class="check-text">{{item}}</label>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="united">
        <label for="id_num_order">{{form.num_order.label}}</label> {{form.num_order}}
        <label for="id_date_order">{{form.date_order.label}}</label> {{form.date_order}}
    </div>
    <div><label for="id_service_TO">{{form.service_TO.label}}</label> {{form.service_TO}}</div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}